#!/bin/bash
set -e -x

cd $(dirname $0)/..
. ./scripts/version

if [[ -z "$COMBARCH" ]]; then
  echo "Combined architecture was not defined, failing build"
  exit 1
fi

IFS=- read RPMARCH GOARCH <<<${COMBARCH}
unset IFS

mkdir -p "/root/rpmbuild/SPECS"

SRC_PATH="/root/rpmbuild/SOURCES/${RPMARCH}"
mkdir -p ${SRC_PATH}

HOME=/root

cp -r /source/rpm/microos/server/* ${SRC_PATH}
cp -r /source/rpm/microos/server/rke2-server.spec /root/rpmbuild/SPECS

CHANGELOG_PATH="${SRC_PATH}/CHANGELOG.md"
touch $CHANGELOG_PATH

. ../gen-changelog "${CHANGELOG_PATH}"

sed -i "s/\%global ARCH.*/\%global ARCH ${GOARCH}/" ${SRC_PATH}/rke2-server.spec

echo "%_topdir /root/rpmbuild" >~/.rpmmacros

cd ${SRC_PATH}

rpmdev-spectool -gf rke2-server.spec \
  --define "rke2_version ${RKE2_VERSION}" \
  --define "changelog_path ${CHANGELOG_PATH}" \
  --define "ARCH ${GOARCH}"

rpmbuild -vv \
  --define "rpm_version ${RPM_VERSION}" \
  --define "rke2_version ${RKE2_VERSION}" \
  --define "rpm_release ${RPM_RELEASE}" \
  --define "changelog_path ${CHANGELOG_PATH}" \
  --define "_sourcedir ${SRC_PATH}" \
  --define "dist .sle" \
  --target ${RPMARCH} \
  -ba ${SRC_PATH}/rke2-server.spec

mkdir -p /source/dist/microos
mkdir -p /source/dist/microos/source
cp -r /root/rpmbuild/RPMS/* /source/dist/microos
cp -r /root/rpmbuild/SRPMS/* /source/dist/microos/source
cp ${CHANGELOG_PATH} /source/dist/microos/CHANGELOG_SERVER.md
