FROM centos:8

RUN for i in $(ls /etc/yum.repos.d); do \
        sed -i -e "s/mirrorlist.*//g" /etc/yum.repos.d/$i && \
        sed -i -e "s/#baseurl=http:\/\/mirror.centos.org/baseurl=http:\/\/linuxsoft.cern.ch\/centos-vault\//g" /etc/yum.repos.d/$i; \
    done && \
    yum install -y epel-release && \
    yum -y install yum-utils rpm-build spectool git jq

WORKDIR /source

COPY . .

ARG COMBARCH
ARG TAG

ENTRYPOINT ["./rpm/centos8/scripts/entry"]
