FROM quay.io/centos/centos:stream10 AS build

RUN dnf install -y epel-release
RUN dnf -y install yum-utils rpm-build git jq rpmdevtools systemd

ENV SOURCE=/source

WORKDIR ${SOURCE}

COPY . .

ARG COMBARCH
ARG TAG
ARG SCRIPT=build

RUN ${SOURCE}/rpm/centos10/scripts/entry "${SCRIPT}"

FROM scratch AS result
ENV SOURCE=/source

COPY --from=build ${SOURCE}/dist /dist