FROM quay.io/centos/centos:stream10

RUN yum install -y epel-release && \
    yum -y install yum-utils rpm-build git jq rpmdevtools systemd

ENV DAPPER_SOURCE /source
ENV DAPPER_OUTPUT ./dist
ENV DAPPER_ENV COMBARCH DRONE_TAG TAG
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./rpm/centos10/scripts/entry"]
