FROM quay.io/centos/centos:stream9 AS build

RUN yum install -y epel-release && \
    yum -y install yum-utils rpm-build git jq rpmdevtools systemd

ENV SOURCE=/source

WORKDIR ${SOURCE}

COPY . .

ARG COMBARCH
ARG TAG
ARG SCRIPT=build

RUN ${SOURCE}/rpm/centos9/scripts/entry "${SCRIPT}"

FROM scratch AS result
ENV SOURCE=/source

COPY --from=build ${SOURCE}/dist /dist
