ARG OPENSUSE=opensuse/leap:15
FROM ${OPENSUSE}

RUN zypper install -y rpm-build git jq rpmdevtools systemd

WORKDIR /source

COPY . .

ARG COMBARCH
ARG TAG

ENTRYPOINT ["./rpm/slemicro/scripts/entry"]
