FROM quay.io/centos/centos:stream9

RUN yum install -y epel-release && \
    yum -y install yum-utils rpm-build git jq rpmdevtools systemd

WORKDIR /source

COPY . .

ARG COMBARCH
ARG TAG

ENTRYPOINT ["./rpm/centos9/scripts/entry"]
