on:
  push:
    branches:
      - master
  pull_request:

name: Build
permissions:
    contents: read
jobs:
  rke2-packaging-centos7-srcrpm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: build-rpm-centos7-srcrpm
      run: |
        make centos7-build
      env:
        COMBARCH: x86_64-amd64
        