#!/bin/bash
set -e -x

cd $(dirname $0)/..
. ./scripts/version

if [[ -z "$COMBARCH" ]]; then
  echo "Combined architecture was not defined, failing build"
  exit 1
fi

IFS=- read RPMARCH GOARCH <<<${COMBARCH}
unset IFS

mkdir -p "/root/rpmbuild/SPECS"

SRC_PATH="/root/rpmbuild/SOURCES/${RPMARCH}"
mkdir -p ${SRC_PATH}

HOME=/root

cp -r /source/rpm/centos8/common/* ${SRC_PATH}
cp -r /source/rpm/centos8/common/rke2-common.spec /root/rpmbuild/SPECS

CHANGELOG_PATH="${SRC_PATH}/CHANGELOG.md"
touch $CHANGELOG_PATH

. ../gen-changelog "${CHANGELOG_PATH}"

sed -i "s/\%global ARCH.*/\%global ARCH ${GOARCH}/" ${SRC_PATH}/rke2-common.spec

cd ${SRC_PATH}

spectool -gf rke2-common.spec \
  --define "rke2_version ${RKE2_VERSION}" \
  --define "changelog_path ${CHANGELOG_PATH}" \
  --define "ARCH ${GOARCH}"

rpmbuild -vv \
  --define "rpm_version ${RPM_VERSION}" \
  --define "rke2_version ${RKE2_VERSION}" \
  --define "rpm_release ${RPM_RELEASE}" \
  --define "changelog_path ${CHANGELOG_PATH}" \
  --define "rke2_policyver ${RKE2_POLICYVER}" \
  --define "_sourcedir ${SRC_PATH}" \
  --target ${RPMARCH} \
  -ba ${SRC_PATH}/rke2-common.spec

mkdir -p /source/dist/centos8
mkdir -p /source/dist/centos8/source
cp -r /root/rpmbuild/RPMS/* /source/dist/centos8
cp -r /root/rpmbuild/SRPMS/* /source/dist/centos8/source
cp ${CHANGELOG_PATH} /source/dist/centos8/CHANGELOG_COMMON.md

