#!/bin/bash
set -e -x

cd $(dirname $0)/..
. ./scripts/version

if [[ -z "$COMBARCH" ]]; then
  echo "Combined architecture was not defined, failing build"
  exit 1
fi

IFS=- read RPMARCH GOARCH <<<${COMBARCH}
unset IFS

mkdir -p "/root/rpmbuild/SPECS"

SRC_PATH="/root/rpmbuild/SOURCES/${RPMARCH}"
mkdir -p ${SRC_PATH}

HOME=/root

cp -r /source/rpm/centos8/agent/* ${SRC_PATH}
cp -r /source/rpm/centos8/agent/rke2-agent.spec /root/rpmbuild/SPECS

CHANGELOG_PATH="/root/rpmbuild/SOURCES/${RPMARCH}/CHANGELOG.md"
touch $CHANGELOG_PATH

. ../gen-changelog "${CHANGELOG_PATH}"

sed -i "s/\%global ARCH.*/\%global ARCH ${GOARCH}/" ${SRC_PATH}/rke2-agent.spec

cd ${SRC_PATH}

spectool -gf rke2-agent.spec \
  --define "rke2_version ${RKE2_VERSION}" \
  --define "changelog_path ${CHANGELOG_PATH}" \
  --define "ARCH ${GOARCH}"

rpmbuild -vv \
  --define "rpm_version ${RPM_VERSION}" \
  --define "rke2_version ${RKE2_VERSION}" \
  --define "rpm_release ${RPM_RELEASE}" \
  --define "changelog_path ${CHANGELOG_PATH}" \
  --define "_sourcedir ${SRC_PATH}" \
  --target ${RPMARCH} \
  -ba ${SRC_PATH}/rke2-agent.spec

mkdir -p /source/dist/centos8
mkdir -p /source/dist/centos8/source
cp -r /root/rpmbuild/RPMS/* /source/dist/centos8
cp -r /root/rpmbuild/SRPMS/* /source/dist/centos8/source
cp /root/rpmbuild/SOURCES/${RPMARCH}/CHANGELOG.md /source/dist/centos8/CHANGELOG_AGENT.md
