#!/bin/bash
set -e -x

cd $(dirname $0)/..
. ./scripts/version

if [[ -z "$COMBARCH" ]]; then
  echo "Combined architecture was not defined, failing build"
  exit 1
fi

IFS=- read RPMARCH GOARCH<<< ${COMBARCH}; unset IFS

HOME=/root
SRC_PATH="${SRC_PATH:-${HOME}/rpmbuild/SOURCES/${RPMARCH}}"

mkdir -p "/root/rpmbuild/SPECS"
mkdir -p "${SRC_PATH}"

cp -r /source/rpm/centos8/server/* "${SRC_PATH}"
cp -r /source/rpm/centos8/server/rke2-server.spec /root/rpmbuild/SPECS

sed -i "s/\%global ARCH.*/\%global ARCH ${GOARCH}/" "${SRC_PATH}/rke2-server.spec"

cd "${SRC_PATH}"

spectool -gf rke2-server.spec \
    --define "rke2_version ${RKE2_VERSION}" \
    --define "ARCH ${GOARCH}"

rpmbuild -vv \
    --define "rpm_version ${RPM_VERSION}" \
    --define "rke2_version ${RKE2_VERSION}" \
    --define "rpm_release ${RPM_RELEASE}" \
    --define "_sourcedir ${SRC_PATH}" \
    --target "${RPMARCH}" \
    -ba "${SRC_PATH}/rke2-server.spec"

mkdir -p /source/dist/centos8
mkdir -p /source/dist/centos8/source
cp -r /root/rpmbuild/RPMS/* /source/dist/centos8
cp -r /root/rpmbuild/SRPMS/* /source/dist/centos8/source
