#!/bin/bash
set -e -x

cd $(dirname $0)/..
. ./scripts/version

if [[ -z "$COMBARCH" ]]; then
  echo "Combined architecture was not defined, failing build"
  exit 1
fi

IFS=- read RPMARCH GOARCH <<<${COMBARCH}
unset IFS

mkdir -p "/root/rpmbuild/SPECS"

SRC_PATH="/root/rpmbuild/SOURCES/${RPMARCH}"
mkdir -p ${SRC_PATH}

HOME=/root

cp -r /source/rpm/slemicro/server/* ${SRC_PATH}
cp -r /source/rpm/slemicro/server/rke2-server.spec /root/rpmbuild/SPECS

CHANGELOG_PATH="/root/rpmbuild/SOURCES/${RPMARCH}/CHANGELOG.md"
touch $CHANGELOG_PATH

. ./scripts/gen-changelog "${CHANGELOG_PATH}"

sed -i "s/\%global ARCH.*/\%global ARCH ${GOARCH}/" ${SRC_PATH}/rke2-server.spec

echo "%_topdir /root/rpmbuild" >~/.rpmmacros

cd ${SRC_PATH}

rpmdev-spectool -gf rke2-server.spec \
  --define "rke2_version ${RKE2_VERSION}" \
  --define "changelog_path ${CHANGELOG_PATH}" \
  --define "ARCH ${GOARCH}"

rpmbuild -vv \
  --define "rpm_version ${RPM_VERSION}" \
  --define "rke2_version ${RKE2_VERSION}" \
  --define "rpm_release ${RPM_RELEASE}" \
  --define "changelog_path ${CHANGELOG_PATH}" \
  --define "_sourcedir ${SRC_PATH}" \
  --define "dist .slemicro" \
  --target ${RPMARCH} \
  -ba ${SRC_PATH}/rke2-server.spec

mkdir -p /source/dist/slemicro
mkdir -p /source/dist/slemicro/source
cp -r /root/rpmbuild/RPMS/* /source/dist/slemicro
cp -r /root/rpmbuild/SRPMS/* /source/dist/slemicro/source
